Fix configuration
sciencemesh/cs3api4lab pull request #102
Opened 2022-02-02 20:26 UTC by diocas

The current code ignores any configuration that is not set in the `config` dict (saw when testing EOS auth, which was complaining that `eos_file` was not set).

I propose we write all the configurations available in the README and only set the default values in `config`.

With my changes, any env variable started with `CS3_` or any value in the json files will be picked, even if nothing uses them.
This way of merging dictionaries is only available in Python 3.9, so I set the minimums in the installation (hope it doesn't break anything).

2022-02-02 20:45 UTC, diocas commented
Btw, the config tests are not ok, otherwise this would've been detected sooner. Please update them.

2022-02-03 17:15 UTC, dagl commented
> Btw, the config tests are not ok, otherwise this would've been detected sooner. Can you please update them?

Which tests do you mean?

2022-02-03 17:20 UTC, diocas commented
@dagl don't we have tests to ensure that the configuration system works? If not, maybe we should xD
But this is not a priority for now

2022-02-03 17:21 UTC, dagl commented
> @dagl don't we have tests to ensure that the configuration system works? If not, maybe we should xD But this is not a priority for now

I don't see any :P. I can add some later.

2022-02-03 19:13 UTC, dagl requested changes
I've created PR to this PR https://github.com/sciencemesh/cs3api4lab/pull/103

2022-02-04 08:17 UTC, diocas commented on cs3api4lab/config/config_manager.py
> +        env_vars = {k[4:].lower():os.environ[k] for k in os.environ if k.startswith("CS3_")}
Done, I guess we can merge it, right?

2022-02-04 09:35 UTC, dagl commented on cs3api4lab/config/config_manager.py
> +        env_vars = {k[4:].lower():os.environ[k] for k in os.environ if k.startswith("CS3_")}
yeah

2022-02-04 09:53 UTC, dagl commented on cs3api4lab/config/config_manager.py
> +        env_vars = {k[4:].lower():os.environ[k] for k in os.environ if k.startswith("CS3_")}
Btw the fix for locks was needed, because environment variables are always strings, so an explicit cast was necessary

2022-02-04 11:00 UTC, diocas commented on cs3api4lab/config/config_manager.py
> +        env_vars = {k[4:].lower():os.environ[k] for k in os.environ if k.startswith("CS3_")}
makes sense. merging

2022-02-04 11:00 UTC, merged