Made OCM optional and temporarily disabled
sciencemesh/cs3api4lab pull request #112
Opened 2022-02-16 18:11 UTC by mateusz-garlacz

2022-02-21 11:48 UTC, diocas requested changes
Please add errors instead of just silently failing. The frontend needs to be aware this is optional and handle attempts from users of sharing with OCM.
Please also rebase.

2022-02-21 11:48 UTC, diocas commented on cs3api4lab/api/share_api_facade.py
> +            else:
We should fail as this request should not reach us. `501`? 
We should do this for all other cases where it applies such an error.

2022-02-22 14:09 UTC, dagl commented
I think we should extend this functionality project-wise, for example in cs3_user_api:find_user_by_query we also try to use ocm

2022-02-22 15:32 UTC, diocas commented
You also try OCM when searching for a users, but you only if it's enabled. I was expecting this PR to fix all those cases (the web part, maybe can come in a 2nd PR).

2022-02-23 18:49 UTC, mateusz-garlacz commented
> You can also try OCM when searching for a users, but you only if it's enabled. I was expecting this PR to fix all those cases (the web part, maybe can come in a 2nd PR).

I updated the PR. What do you mean by web part ?

2022-02-24 14:40 UTC, diocas reviewed
Just one last comment and we can merge.

What I meant about the web is that it should not receive the errors you just added. Those are for anyone trying to circumvent the API. The web should prevent any attempt to use OCM if it's not available. I don't know if that's already the case, but I would expect it to be (for example, if searching for a user the OCM options do not appear, it's expectable that they are not used when creating a share so all is good). So this was just a remark :)

2022-02-24 14:40 UTC, diocas commented on cs3api4lab/api/cs3_user_api.py
>          ocm_response = self.invite_api.FindAcceptedUsers(ia.FindAcceptedUsersRequest(filter=query),
Shouldn't this be inside the if as well?

2022-02-25 13:52 UTC, diocas commented
@mateusz-garlacz when you removed the ocm handlers you forgot to remove the import and LGTM is now complaining. (and thanks for removing the handlers, now we really have a unified api!)

2022-02-25 21:28 UTC, mateusz-garlacz commented
Ah sorry, my bad. Now I made lgtm happy

2022-02-28 17:09 UTC, merged