Traitlets config
sciencemesh/cs3api4lab pull request #175
Opened 2022-06-23 21:25 UTC by diocas

Replacement for #173: I've rebased on the latest master after merging the drives names PR. So it should be exactly the same (with addition of `mount_dir`).

Once #174 gets merged, I'll rebase and see if the tests succeed (but feel free to have a look if you have time).

Closes #148 
Closes #109

2022-06-23 23:20 UTC, mateusz-garlacz approved these changes

2022-06-28 21:19 UTC, mateusz-garlacz requested changes
Hi, something went wrong with this rebase, it does not build. I rebased my branch SoftwareMind-ScienceMesh-org:traitlets_config and resolved conflicts. Please let me know if I can recreate this https://github.com/sciencemesh/cs3api4lab/pull/173

2022-06-29 07:19 UTC, diocas commented
@mateusz-garlacz yep, feel free to re-open the other and I'll close this

2022-06-29 07:19 UTC, diocas commented
But we still need to rebase on top of the tests, which is not merged yet.

2022-07-26 13:52 UTC, closed without merging